[project]
name = "shiv-demo"
version = "0.1.0"
description = "shiv demo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "pip>=24.3.1",
    "pytest>=8.3.4",
    "setuptools>=75.6.0",
]
